spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hibernate_ex
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#  liquibase:
#    change-log: classpath:db/liquibase-changeLog.xml

  thymeleaf:
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/auth/realms/master

server:
  port: 8080
